services:
  frontend:
    build:
      context: .
      target: development
    container_name: othello-frontend
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
    command: npm run serve

  test:
    build:
      context: .
      target: test
    container_name: othello-test
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=test
    command: npm run test:unit
